# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_RustIRT_wrappers", use_symbols = TRUE, package_name = "RustIRT")

#' @usage NULL
#' @useDynLib RustIRT, .registration = TRUE
NULL

fit_RustIRT <- function(Y, alpha, beta, theta, a0, A0, b0, B0, theta_constraint, theta_strict_identification, maxit, verbose, tol) .Call(wrap__fit_RustIRT, Y, alpha, beta, theta, a0, A0, b0, B0, theta_constraint, theta_strict_identification, maxit, verbose, tol)


# nolint end
